### ISSUE TITLE
This API project is not authorized to use this API

### ISSUE THREAD

**Issue by dabonnestor** [shukerullah/react-geocode#33]
Server returned status code REQUEST_DENIED

**Comment by kel29** [comment]
I had this same issue. Turns out, you also need to enable the Geocoding API through Google's Developer Console. At least, that was my problem. To do this:
- Visit [Google Developer Console](https://console.developers.google.com/)
- Make sure you have selected the correct project (top left you should see the project's name, or a drop down to select a different one/create a new one if needed)
- From the menu bar on the left, go to APIs & Services -> Library
- Search for Geocoding API, or find it in the Maps section. Click into it and hit the blue Enable button. If it is already enabled, the button will instead say Manage, and will have a green checkmark with 'API enabled' next to it.

This resolved the issue for me. I am only converting addresses to coordinates, and don't know if you would need to enable any other libraries if you were trying to convert coordinates to an address.

**Comment by blwinters** [comment]
I had mistakenly enabled Geolocation instead of Geocoding, whoops!

**Comment by busharthussain** [comment]
dd
